### ISSUE TITLE
Failing on ubuntu xenial

### ISSUE THREAD

**Issue by TeoTN** [kschu91/puppet-gogs#16]
Hi!
I am experiencing issues with puppet-gogs on ubuntu xenial. It fails on starting service (I also tried running with default config, i.e. `include ::gogs`)
```
Error: Could not start Service[gogs]: Execution of '/bin/systemctl start gogs' returned 5: Failed to start gogs.service: Unit gogs.service not found.
Error: /Stage[main]/Gogs::Service/Service[gogs]/ensure: change from stopped to running failed: Could not start Service[gogs]: Execution of '/bin/systemctl start gogs' returned 5: Failed to start gogs.service: Unit gogs.service not found.
```
The problem might be related with [this one](https://discuss.gogs.io/t/gogs-ubuntu-15-no-start/185/8)

**Comment by kschu91** [comment]
Hi TeoTN,
Could you please navigate to the gogs home directory (should be `/opt/gogs` by default) as gogs user (`git` by default) and try to run `/opt/gogs/gogs web` manually?
systemctl is not very helpful in terms of error messages. Could be just a configuration issue.

**Comment by kschu91** [comment]
Hi TeoTN,
Can I close this issue?
Cheers,
Kevin

**Comment by TeoTN** [comment]
I've migrated to other solution on docker swarm and didn't have chance to verify. Thanks for help though!
