### ISSUE TITLE
"owner" parameter does not appear to work

### ISSUE THREAD

**Issue by wfsaxton** [kschu91/puppet-gogs#4]
I have the following gogs class:

    class { 'gogs':
        version => '0.9.141',

        app_ini => {
            'APP_NAME' => 'SWR GIT Service'
        },

        app_ini_sections => {

            'server'   => {
                'DOMAIN'    => 'gitserver.example.com',
                'HTTP_PORT' => 8080,
            },
          'database' => {
                'DB_TYPE' => 'postgres',
                'HOST'    => 'localhost:5432',
                'NAME'    => 'gogs',
                'USER'    => 'gogs',
                'PASSWD'  => 'gogspasswd',
            },
            'security' => {
                'SECRET_KEY' => 'mysecretkey',
                'INSTALL_LOCK' => true,
            },
        },

        manage_user => false,
        manage_home => false,

        require => [
            USER[[swradm]],
            GROUP[[swr]],
        ],

        owner       => 'swradm',
        group       => 'swr',

        sysconfig => {
            'NAME' => { value => 'gogs' },
            'USER' => { value => 'swradm' },
        }
    }

When I run puppet, here is the state of my app.ini:

    [vagrant@gitserver ~]$ cat /opt/gogs/custom/conf/app.ini
    APP_NAME=SWR GIT Service
    RUN_USER=git
    RUN_MODE=prod

**Comment by wfsaxton** [comment]
Hmm, perhaps this is just a mistake in the documentation.  I see in the module that "owner" really only sets the ownership of the files, not what user runs gogs.  However, the documentation for the "owner" parameter says:

"Use this parameter to change the user under which Gogs is running. By default the users name is git."

In order to truly run as a different user, the "RUN_USER" variable needs to be set in the "app_ini" parameter.

**Comment by kschu91** [comment]
Hi wfsaxton,

thanks for issuing your problem. It seems like I have forgotten to set the `RUN_USER` configuration with the given `owner` parameter. I will fix that as soon as possible.

You should be able fix this with a workaround like that:
```
...
app_ini => {
    'RUN_USER' => 'swradm'
},
...
```
Does this work for you?

**Comment by kschu91** [comment]
But for the sysconfig the `owner` parameter should work. The module is changing the sysconfig values depending on your distribution and configured user. So that you normally don´t have to configure the user in sysconfig manually.

I´ll try this out later. Maybe there is a bug too.

**Comment by wfsaxton** [comment]
Yes, the RUN_USER setting worked for me.  Er, rather, it did properly set the RUN_USER variable in app_ini (still haven't gotten gogs to work using Linux systemctl but...I think that's an issue on my end).

**Comment by kschu91** [comment]
I had the same problems while testing. Make sure all variables defined in the init scripts are valid and the directories exists and have the right permissions for your user. systemctl will fail silently otherwise.

Additionally using variables in your custom sysconfig that are only defined in the init file does not work. Workaround is to define them in custom syconfig too.

For example:
```
    sysconfig => {
        'FOO' => { value => '${BAR}' },
    }
```

While `BAR` is only defined in the original init script it will not be interpolated.

**Comment by kschu91** [comment]
Maybe it is the `LOGPATH` if you are using CentOS?

And make sure you have:
```
    sysconfig => {
        'GOGS_USER' => { value => 'swradm' },
    }
```

**Comment by wfsaxton** [comment]
Yeah, I hate how it all fails silently.  I finally figured out the combination of sysconfig/api.ini combinations to finally get it working.  

My only issue now is that I have to run puppet apply twice in order to getting it to run.  My hunch is that its a puppet ordering issue with user accounts, postgres, or something else...at least I'm getting closer to a solution.

**Comment by kschu91** [comment]
There is currently a new major version [building on travis](https://travis-ci.org/kschu91/puppet-gogs/builds/206269845). As soon as it´s done you can download the new version from forge.

With the new version you should be able to run gogs with a different user without changing any sysconfig by yourself.
Please also note that the parameter sysconfig has changed a bit compared to the last version.

Please let me know if that fixes your issue.

**Comment by wfsaxton** [comment]
Thanks.  Will check it out.

**Comment by kschu91** [comment]
#6

**Comment by kschu91** [comment]
@wfsaxton does the new release fix your issue?

**Comment by wfsaxton** [comment]
@kschu91 The only issue for me on your end was documentation.  Everything worked fine for me once I figured out how to set RUN_USER and also add puppet dependencies to make sure the DB was created before starting gogs.

What change did you make?  Did you make "owner" also manage the "RUN_USER" setting or something?

**Comment by kschu91** [comment]
> What change did you make? Did you make "owner" also manage the "RUN_USER" setting or something?

Correct. Thats exactly what the new version does.
Therefore you don´t need to configure any sysconfig values by yourself since version 1.0.0. It should be enough to use the `owner` parameter.

**Comment by wfsaxton** [comment]
Was going to test this out, but I moved over to using Oracle Linux which this module doesn't currently support.

Will try to find time to spin up a Centos node to re-test this...but if you happen to implement https://github.com/kschu91/puppet-gogs/issues/10 before then, I'll text it on Oracle Linux instead.

**Comment by wfsaxton** [comment]
I verified this worked on Centos 7.
